sudo: required
language: java
jdk: oraclejdk8
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: code-deploy-us-east-1-beta
  region: us-east-1
  local_dir: target
  skip_cleanup: true
  on:
    repo: jack53519/ProxilyBackend
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  application: proxily
  key: CombinedService.jar
  deployment_group: proxily-deployment-group
  bucket: code-deploy-us-east-1-beta
  bundle_type: jar

install: true
script: mvn clean install
