version: 0.0
os: linux
files:
  - source: ./
    destination: /var/server
permissions:
  - object: /var/server
    owner: ec2-user
    mode: 777
    type:
    - file
hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh
      runas: root