version: 0.0
os: linux
files:
  - source: ./
    destination: /var/server/
hooks:
  BeforeInstall:
    - location: scripts/start-silent.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh
      runas: root